---
sidebar: sidebar 
permalink: get-started/cache-intro.html 
keywords: how volume caching works, what is volume caching, bluexp 
summary: 卷缓存在远程位置提供持久的、可写的卷。您可以使用卷缓存来加快数据访问速度或卸载访问频繁的卷的流量。缓存卷非常适合读取密集型工作负载，尤其是客户端需要重复访问相同数据的情况。 
---
= 了解卷缓存
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
卷缓存是ONTAP 9 软件的一项功能，它是一种远程缓存功能，可简化文件分发，通过将资源靠近用户和计算资源的位置来减少 WAN 延迟，并降低 WAN 带宽成本。卷缓存在远程位置提供持久的、可写的卷。您可以使用卷缓存来加快数据访问速度或卸载访问量大的卷的流量。缓存卷非常适合读取密集型工作负载，尤其是客户端需要重复访问相同数据的情况。

通过卷缓存，您可以获得云的缓存功能，特别是针对Amazon FSx for NetApp ONTAP、 Cloud Volumes ONTAP和本地工作环境。

卷缓存还为分支机构提供了对公司数据集的访问。通过提供_热数据_（需要从集群中的多个控制器频繁访问的数据），您可以提高交付给关键应用程序的性能。而且，通过缓存位于世界各地多个位置的用户本地热数据，您可以通过同时访问集中数据集来增强他们的协作，同时还可以减少他们访问热数据时收到的响应时间。



== NetApp Console

可以通过NetApp Console访问卷缓存。

NetApp Console提供企业级跨本地和云环境的NetApp存储和数据服务的集中管理。需要控制台才能访问和使用NetApp数据服务。作为管理界面，它使您能够从一个界面管理许多存储资源。控制台管理员可以控制企业内所有系统的存储和服务的访问。

您不需要许可证或订阅即可开始使用NetApp Console，并且只有当您需要在云中部署控制台代理以确保与存储系统或NetApp数据服务的连接时才需要付费。但是，一些可从控制台访问的NetApp数据服务是需要许可或基于订阅的。

详细了解 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["NetApp Console"]。



== 什么是缓存？

缓存是位于主机和数据源之间的临时存储位置。缓存的目的是存储源数据中经常访问的部分，以便以比从源获取数据更快的速度提供数据。缓存在读取密集型环境中最有用，在这种环境中数据被访问多次并由多个主机共享。缓存系统比有数据源的系统更快，这是通过更快的存储系统和缓存存储空间与主机的接近性实现的。



== 卷缓存的好处

卷缓存具有以下优势：

* 加速混合云基础设施的性能
* 通过将数据从一个云提供商缓存到另一个云提供商来消除云孤岛
* 降低存储成本
* 跨地理位置协作
* 能够更快地适应不断变化的 IT 环境
* 按需或基于订阅的云中托管卷缓存




== 使用卷缓存可以做什么

卷缓存可让您充分利用多种NetApp技术来实现以下目标：

* 将数据从一个云提供商缓存到另一个云提供商
* 查看和编辑缓存导出策略
* 调整现有缓存的大小
* 删除缓存




== 成本

NetApp不会向您收取卷缓存费用，但您需要检查您的云提供商是否有适用的数据入口和出口费用。



== 许可

卷缓存不需要特殊的ONTAP许可证。



== 卷缓存的工作原理

缓存卷是由源卷支持的稀疏填充卷。缓存卷可以与源卷位于同一集群上，也可以位于不同的集群上。

缓存卷提供对源卷中的数据的访问，而不需要所有数据都在缓存卷中。通过仅保留热数据（工作数据或最近使用的数据），可以有效地管理缓存卷中的数据存储。

如果缓存卷包含客户端请求的数据，则卷缓存读取请求。否则，卷缓存服务会从源卷请求数据并在满足客户端请求之前存储数据。随后的数据请求将直接从缓存卷中提供。这可以提高重复访问相同数据时的性能，因为在第一次请求之后，数据不再需要通过网络传输或由过载的系统提供服务。
